# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ImGui_config = debug
  ImGuizmo_config = debug
endif
ifeq ($(config),release)
  ImGui_config = release
  ImGuizmo_config = release
endif
ifeq ($(config),dist)
  ImGui_config = dist
  ImGuizmo_config = dist
endif

PROJECTS := ImGui ImGuizmo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C imgui -f Makefile config=$(ImGui_config)
endif

ImGuizmo: ImGui
ifneq (,$(ImGuizmo_config))
	@echo "==== Building ImGuizmo ($(ImGuizmo_config)) ===="
	@${MAKE} --no-print-directory -C . -f ImGuizmo.make config=$(ImGuizmo_config)
endif

clean:
	@${MAKE} --no-print-directory -C imgui -f Makefile clean
	@${MAKE} --no-print-directory -C . -f ImGuizmo.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   ImGuizmo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"